/*
 * compat/utils/walkers.c
 *
 * Ported from Apache Cloudberry (src/backend/optimizer/util/walkers.c).
 * Adapted for PostgreSQL 18 single-node mode: CBDB-only plan node types
 * (Motion, ShareInputScan, Sequence, PartitionSelector, Dynamic* scans,
 * SplitUpdate, AssertOp, Flow, TupleSplit, DQAExpr, RuntimeFilter,
 * TableFunctionScan, TableValueExpr) are omitted — they are never
 * generated by pg_orca and do not exist in PG18's NodeTag enum.
 *
 * Abstract base tags T_Plan, T_Scan, T_Join also do not exist in PG18
 * and are omitted accordingly.
 *
 * Only extract_nodes_plan() and its helpers are ported here; that is the
 * only entry point currently needed by gpdbwrappers.cpp.
 */

#include "postgres.h"

#include "miscadmin.h"
#include "nodes/nodeFuncs.h"
#include "nodes/plannodes.h"
#include "optimizer/optimizer.h"

/* -----------------------------------------------------------------------
 * Internal types
 * ----------------------------------------------------------------------- */

/*
 * Minimal plan_tree_base_prefix: first field of every walker context.
 * extract_nodes_walker passes NULL as the base (no SubPlan lookup needed).
 */
typedef struct plan_tree_base_prefix
{
	Node	   *node;			/* PlannerInfo* or PlannedStmt*, may be NULL */
} plan_tree_base_prefix;

typedef struct extract_context
{
	plan_tree_base_prefix base; /* Required first field */
	List	   *nodes;
	NodeTag		nodeTag;
	bool		descendIntoSubqueries;
} extract_context;

/* -----------------------------------------------------------------------
 * Typed walker callback — avoids "no prototype" warnings
 * ----------------------------------------------------------------------- */
typedef bool (*node_walker_fn) (Node *node, void *context);

/* -----------------------------------------------------------------------
 * Forward declarations
 * ----------------------------------------------------------------------- */

static bool plan_tree_walker(Node *node, node_walker_fn walker,
							 void *context, bool recurse_into_subplans);
static bool extract_nodes_walker(Node *node, extract_context *context);

/* -----------------------------------------------------------------------
 * walk_plan_node_fields — walk the common Plan fields
 * ----------------------------------------------------------------------- */

static bool
walk_plan_node_fields(Plan *plan, node_walker_fn walker, void *context)
{
	if (walker((Node *) plan->targetlist, context))
		return true;
	if (walker((Node *) plan->qual, context))
		return true;
	if (walker((Node *) plan->lefttree, context))
		return true;
	if (walker((Node *) plan->righttree, context))
		return true;
	if (walker((Node *) plan->initPlan, context))
		return true;
	return false;
}

static bool
walk_scan_node_fields(Scan *scan, node_walker_fn walker, void *context)
{
	return walk_plan_node_fields((Plan *) scan, walker, context);
}

static bool
walk_join_node_fields(Join *join, node_walker_fn walker, void *context)
{
	if (walk_plan_node_fields((Plan *) join, walker, context))
		return true;
	return walker((Node *) join->joinqual, context);
}

/* -----------------------------------------------------------------------
 * plan_tree_walker — general Plan-tree walker for PG18
 *
 * CBDB-only node types and abstract base tags (T_Plan, T_Scan, T_Join)
 * are omitted; unknown tags fall through to expression_tree_walker.
 * ----------------------------------------------------------------------- */

static bool
plan_tree_walker(Node *node,
				 node_walker_fn walker,
				 void *context,
				 bool recurse_into_subplans)
{
	if (node == NULL)
		return false;

	check_stack_depth();

	switch (nodeTag(node))
	{
		case T_Result:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			if (walker((Node *) ((Result *) node)->resconstantqual, context))
				return true;
			break;

		case T_ProjectSet:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			break;

		case T_Append:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			if (walker((Node *) ((Append *) node)->appendplans, context))
				return true;
			break;

		case T_MergeAppend:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			if (walker((Node *) ((MergeAppend *) node)->mergeplans, context))
				return true;
			break;

		case T_RecursiveUnion:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			break;

		case T_BitmapAnd:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			if (walker((Node *) ((BitmapAnd *) node)->bitmapplans, context))
				return true;
			break;

		case T_BitmapOr:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			if (walker((Node *) ((BitmapOr *) node)->bitmapplans, context))
				return true;
			break;

		case T_SeqScan:
		case T_SampleScan:
		case T_BitmapHeapScan:
		case T_WorkTableScan:
		case T_NamedTuplestoreScan:
			if (walk_scan_node_fields((Scan *) node, walker, context))
				return true;
			break;

		case T_ForeignScan:
			if (walk_scan_node_fields((Scan *) node, walker, context))
				return true;
			if (walker((Node *) ((ForeignScan *) node)->fdw_exprs, context))
				return true;
			break;

		case T_CustomScan:
			if (walk_scan_node_fields((Scan *) node, walker, context))
				return true;
			if (walker((Node *) ((CustomScan *) node)->custom_plans, context))
				return true;
			if (walker((Node *) ((CustomScan *) node)->custom_exprs, context))
				return true;
			if (walker((Node *) ((CustomScan *) node)->custom_scan_tlist, context))
				return true;
			break;

		case T_ValuesScan:
			if (walker((Node *) ((ValuesScan *) node)->values_lists, context))
				return true;
			if (walk_scan_node_fields((Scan *) node, walker, context))
				return true;
			break;

		case T_TableFuncScan:
			if (walker((Node *) ((TableFuncScan *) node)->tablefunc, context))
				return true;
			if (walk_scan_node_fields((Scan *) node, walker, context))
				return true;
			break;

		case T_FunctionScan:
			if (walker((Node *) ((FunctionScan *) node)->functions, context))
				return true;
			if (walk_scan_node_fields((Scan *) node, walker, context))
				return true;
			break;

		case T_IndexScan:
			if (walk_scan_node_fields((Scan *) node, walker, context))
				return true;
			if (walker((Node *) ((IndexScan *) node)->indexqual, context))
				return true;
			break;

		case T_IndexOnlyScan:
			if (walk_scan_node_fields((Scan *) node, walker, context))
				return true;
			if (walker((Node *) ((IndexOnlyScan *) node)->indexqual, context))
				return true;
			break;

		case T_BitmapIndexScan:
			if (walk_scan_node_fields((Scan *) node, walker, context))
				return true;
			if (walker((Node *) ((BitmapIndexScan *) node)->indexqual, context))
				return true;
			break;

		case T_TidScan:
			if (walk_scan_node_fields((Scan *) node, walker, context))
				return true;
			if (walker((Node *) ((TidScan *) node)->tidquals, context))
				return true;
			break;

		case T_TidRangeScan:
			if (walk_scan_node_fields((Scan *) node, walker, context))
				return true;
			if (walker((Node *) ((TidRangeScan *) node)->tidrangequals, context))
				return true;
			break;

		case T_SubqueryScan:
			if (walk_scan_node_fields((Scan *) node, walker, context))
				return true;
			if (walker((Node *) ((SubqueryScan *) node)->subplan, context))
				return true;
			break;

		case T_NestLoop:
			if (walk_join_node_fields((Join *) node, walker, context))
				return true;
			break;

		case T_MergeJoin:
			if (walk_join_node_fields((Join *) node, walker, context))
				return true;
			if (walker((Node *) ((MergeJoin *) node)->mergeclauses, context))
				return true;
			break;

		case T_HashJoin:
			if (walk_join_node_fields((Join *) node, walker, context))
				return true;
			if (walker((Node *) ((HashJoin *) node)->hashclauses, context))
				return true;
			break;

		case T_Material:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			break;

		case T_Sort:
		case T_IncrementalSort:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			break;

		case T_Agg:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			break;

		case T_WindowAgg:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			if (walker(((WindowAgg *) node)->startOffset, context))
				return true;
			if (walker(((WindowAgg *) node)->endOffset, context))
				return true;
			break;

		case T_Unique:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			break;

		case T_Gather:
		case T_GatherMerge:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			break;

		case T_Hash:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			break;

		case T_SetOp:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			break;

		case T_Limit:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			if (walker((Node *) ((Limit *) node)->limitCount, context))
				return true;
			if (walker((Node *) ((Limit *) node)->limitOffset, context))
				return true;
			break;

		case T_LockRows:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			break;

		case T_ModifyTable:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			if (walker((Node *) ((ModifyTable *) node)->withCheckOptionLists, context))
				return true;
			if (walker((Node *) ((ModifyTable *) node)->onConflictSet, context))
				return true;
			if (walker((Node *) ((ModifyTable *) node)->onConflictWhere, context))
				return true;
			if (walker((Node *) ((ModifyTable *) node)->returningLists, context))
				return true;
			if (walker((Node *) ((ModifyTable *) node)->mergeActionLists, context))
				return true;
			break;

		case T_Memoize:
			if (walk_plan_node_fields((Plan *) node, walker, context))
				return true;
			if (walker((Node *) ((Memoize *) node)->param_exprs, context))
				return true;
			break;

		case T_CteScan:
			if (walk_scan_node_fields((Scan *) node, walker, context))
				return true;
			break;

		case T_SubPlan:
			{
				SubPlan    *subplan = (SubPlan *) node;

				if (expression_tree_walker((Node *) subplan->testexpr,
										   walker, context))
					return true;
				if (expression_tree_walker((Node *) subplan->args,
										   walker, context))
					return true;
				/*
				 * Do not recurse into the subplan's Plan tree here —
				 * extract_nodes_walker intentionally stops at SubPlan
				 * boundaries (matches Cloudberry behavior, see MPP-17168).
				 */
			}
			break;

		case T_IntList:
		case T_OidList:
			break;

		case T_Query:
			return query_tree_walker((Query *) node, walker, context, 0);

		default:
			return expression_tree_walker(node, walker, context);
	}

	return false;
}

/* -----------------------------------------------------------------------
 * extract_nodes_walker — internal recursive walker
 * ----------------------------------------------------------------------- */

static bool
extract_nodes_walker(Node *node, extract_context *context)
{
	if (node == NULL)
		return false;

	if (nodeTag(node) == context->nodeTag)
		context->nodes = lappend(context->nodes, node);

	if (nodeTag(node) == T_SubPlan)
	{
		SubPlan    *subplan = (SubPlan *) node;

		/*
		 * Walk SubPlan expressions even when !descendIntoSubqueries.
		 * Do not descend into the subplan's Plan tree (see MPP-17168).
		 */
		if (extract_nodes_walker((Node *) subplan->testexpr, context))
			return true;
		if (expression_tree_walker((Node *) subplan->args,
								   (node_walker_fn) extract_nodes_walker,
								   context))
			return true;
		return false;
	}

	if (nodeTag(node) == T_SubqueryScan && !context->descendIntoSubqueries)
		return false;

	return plan_tree_walker(node,
							(node_walker_fn) extract_nodes_walker,
							(void *) context,
							true);
}

/* -----------------------------------------------------------------------
 * extract_nodes_plan — public entry point
 *
 * Walk a Plan tree rooted at 'pl' and collect all nodes whose NodeTag
 * matches 'nodeTag'.  If 'descendIntoSubqueries' is false, SubqueryScan
 * subtrees are skipped.
 * ----------------------------------------------------------------------- */

List *
extract_nodes_plan(Plan *pl, int nodeTag, bool descendIntoSubqueries)
{
	extract_context context;

	Assert(pl);
	context.base.node = NULL;
	context.nodes = NIL;
	context.nodeTag = (NodeTag) nodeTag;
	context.descendIntoSubqueries = descendIntoSubqueries;
	extract_nodes_walker((Node *) pl, &context);
	return context.nodes;
}
